websites = {
    # Existing entries...
    "github" : "www.github.com",
    "youtube" : "www.youtube.com",
    "facebook" : "www.facebook.com",
    "twitter" : "www.twitter.com",
    "instagram" : "www.instagram.com",
    "linkedin" : "www.linkedin.com",
    "reddit" : "www.reddit.com",
    "pinterest" : "www.pinterest.com",
    "quora" : "www.quora.com",
    "tumblr" : "www.tumblr.com",
    "flickr" : "www.flickr.com",
    "snapchat" : "www.snapchat.com",
    "tiktok" : "www.tiktok.com",
    "vimeo" : "www.vimeo.com",
    "dropbox" : "www.dropbox.com",
    "onedrive" : "www.onedrive.com",
    "google drive" : "drive.google.com",
    "icloud" : "www.icloud.com",
    "amazon" : "www.amazon.com",
    "ebay" : "www.ebay.com",
    "alibaba" : "www.alibaba.com",
    "netflix" : "www.netflix.com",
    "hulu" : "www.hulu.com",
    "disney plus" : "www.disneyplus.com",
    "hbo max" : "www.hbomax.com",
    "spotify" : "www.spotify.com",
    "soundcloud" : "www.soundcloud.com",
    "apple music" : "www.apple.com/apple-music",
    "pandora" : "www.pandora.com",
    "deezer" : "www.deezer.com",
    "bandcamp" : "www.bandcamp.com",
    "bbc" : "www.bbc.com",
    "cnn" : "www.cnn.com",
    "nytimes" : "www.nytimes.com",
    "the guardian" : "www.theguardian.com",
    "forbes" : "www.forbes.com",
    "bloomberg" : "www.bloomberg.com",
    "reuters" : "www.reuters.com",
    "espn" : "www.espn.com",
    "fox news" : "www.foxnews.com",
    "nbc news" : "www.nbcnews.com",
    "cbs news" : "www.cbsnews.com",
    "abc news" : "www.abcnews.go.com",
    "msnbc" : "www.msnbc.com",
    "npr" : "www.npr.org",
    "wsj" : "www.wsj.com",
    "yahoo news" : "news.yahoo.com",
    "buzzfeed" : "www.buzzfeed.com",
    "huffpost" : "www.huffpost.com",
    "canva" : "www.canva.com",
    "chatgpt" : "chat.openai.com",
    "slack" : "www.slack.com",
    "trello" : "www.trello.com",
    "asana" : "www.asana.com",
    "zoom" : "www.zoom.us",
    "skype" : "www.skype.com",
    "microsoft teams" : "www.microsoft.com/microsoft-teams",
    "google meet" : "meet.google.com",
    "webex" : "www.webex.com",
    "jira" : "www.atlassian.com/software/jira",
    "notion" : "www.notion.so",
    "airtable" : "www.airtable.com",
    "monday" : "www.monday.com",
    "clickup" : "www.clickup.com",
    "dropbox paper" : "www.dropbox.com/paper",
    "confluence" : "www.atlassian.com/software/confluence",
    "figma" : "www.figma.com",
    "adobe xd" : "www.adobe.com/products/xd.html",
    "invision" : "www.invisionapp.com",
    "microsoft word" : "www.microsoft.com/microsoft-365/word",
    "google docs" : "docs.google.com",
    "medium" : "www.medium.com",
    "wordpress" : "www.wordpress.com",
    "wix" : "www.wix.com",
    "squarespace" : "www.squarespace.com",
    "shopify" : "www.shopify.com",
    "bigcommerce" : "www.bigcommerce.com",
    "weebly" : "www.weebly.com",
    "godaddy" : "www.godaddy.com",
    "namecheap" : "www.namecheap.com",
    "bluehost" : "www.bluehost.com",
    "siteground" : "www.siteground.com",
    "hostgator" : "www.hostgator.com",
    "dreamhost" : "www.dreamhost.com",
    "a2 hosting" : "www.a2hosting.com",
    "inmotion hosting" : "www.inmotionhosting.com",
    "digitalocean" : "www.digitalocean.com",
    "linode" : "www.linode.com",
    "aws" : "aws.amazon.com",
    "azure" : "azure.microsoft.com",
    "google cloud" : "cloud.google.com",
    "heroku" : "www.heroku.com",
    "gitlab" : "www.gitlab.com",
    "bitbucket" : "bitbucket.org",
    "codepen" : "codepen.io",
    "jsfiddle" : "jsfiddle.net",
    "repl.it" : "repl.it",
    "stack overflow" : "stackoverflow.com",
    "stackoverflow careers" : "stackoverflow.com/jobs",
    "glassdoor" : "www.glassdoor.com",
    "indeed" : "www.indeed.com",
    "linkedin jobs" : "www.linkedin.com/jobs",
    "monster" : "www.monster.com",
    "simplyhired" : "www.simplyhired.com",
    "angel.co" : "angel.co",
    "github jobs" : "jobs.github.com",
    "ziprecruiter" : "www.ziprecruiter.com",
    "careerbuilder" : "www.careerbuilder.com",
    "snagajob" : "www.snagajob.com",
    "dice" : "www.dice.com",
    "jobs" : "www.jobs.com",
    "bamboohr" : "www.bamboohr.com",
    "workday" : "www.workday.com",
    "adp" : "www.adp.com",
    "sap successfactors" : "www.sap.com/products/hcm.html",
    "oracle hcm" : "www.oracle.com/applications/human-capital-management",
    "zenefits" : "www.zenefits.com",
    "paycor" : "www.paycor.com",
    "paycom" : "www.paycom.com",
    "gusto" : "www.gusto.com",
    "square" : "squareup.com",
    "stripe" : "www.stripe.com",
    "paypal" : "www.paypal.com",
    "venmo" : "www.venmo.com",
    "cash app" : "cash.app",
    "robinhood" : "www.robinhood.com",
    "etrade" : "www.etrade.com",
    "fidelity" : "www.fidelity.com",
    "charles schwab" : "www.schwab.com",
    "vanguard" : "investor.vanguard.com",
    "td ameritrade" : "www.tdameritrade.com",
    "coinbase" : "www.coinbase.com",
    "binance" : "www.binance.com",
    "kraken" : "www.kraken.com",
    "blockchain" : "www.blockchain.com",
    "gemini" : "www.gemini.com",
    "bitfinex" : "www.bitfinex.com",
    "bitstamp" : "www.bitstamp.net",
    "bittrex" : "www.bittrex.com",
    "okex" : "www.okex.com",
    "poloniex" : "www.poloniex.com",
    "coindesk" : "www.coindesk.com",
    "cointelegraph" : "www.cointelegraph.com",
    "decrypt" : "www.decrypt.co",
    "cryptoslate" : "www.cryptoslate.com",
    "cryptonews" : "www.cryptonews.com",
    "coinmarketcap" : "www.coinmarketcap.com",
    "coingecko" : "www.coingecko.com",
    "messari" : "www.messari.io",
    "icodrops" : "www.icodrops.com",
    "tokenmarket" : "www.tokenmarket.net",
    "coinpaprika" : "www.coinpaprika.com",
    "cryptocompare" : "www.cryptocompare.com",
    "coincheckup" : "www.coincheckup.com",
    "cryptobriefing" : "www.cryptobriefing.com",
    "blockonomi" : "www.blockonomi.com",
    "coininsider" : "www.coininsider.com",
    "newsbtc" : "www.newsbtc.com",
    "bitcoin.com" : "www.bitcoin.com",
    "ethereum.org" : "www.ethereum.org",
    "litecoin.com" : "www.litecoin.com",
    "ripple.com" : "www.ripple.com",
    "cardano.org" : "www.cardano.org",
    "stellarlumens.com" : "www.stellarlumens.com",
    "tezos.com" : "www.tezos.com",
    "eos.io" : "www.eos.io",
    "neo.org" : "www.neo.org",
    "iota.org" : "www.iota.org",
    "monero.org" : "www.monero.org",
    "zcash.org" : "www.zcash.org",
    "dash.org" : "www.dash.org",
    "dogecoin.com" : "www.dogecoin.com",
    "gpt" : "www.chatgpt.com/",

    # New entries:
    "duckduckgo" : "www.duckduckgo.com",
    "wikipedia" : "www.wikipedia.org",
    "stackexchange" : "www.stackexchange.com",
    "medium" : "www.medium.com",
    "quora" : "www.quora.com",
    "github" : "www.github.com",
    "codewars" : "www.codewars.com",
    "freecodecamp" : "www.freecodecamp.org",
    "edx" : "www.edx.org",
    "coursera" : "www.coursera.org",
    "khan academy" : "www.khanacademy.org",
    "udacity" : "www.udacity.com",
    "udemy" : "www.udemy.com",
    "codecademy" : "www.codecademy.com",
    "pluralsight" : "www.pluralsight.com",
    "learnpython" : "www.learnpython.org",
    "python.org" : "www.python.org",
    "numpy" : "numpy.org",
    "pandas" : "pandas.pydata.org",
    "scipy" : "www.scipy.org",
    "matplotlib" : "matplotlib.org",
    "jupyter" : "jupyter.org",
    "kaggle" : "www.kaggle.com",
    "towards data science" : "towardsdatascience.com",
    "arxiv" : "www.arxiv.org",
    "semanticscholar" : "www.semanticscholar.org",
    "google scholar" : "scholar.google.com",
    "researchgate" : "www.researchgate.net",
    "pubmed" : "pubmed.ncbi.nlm.nih.gov",
    "sciencedirect" : "www.sciencedirect.com",
    "springer" : "link.springer.com",
    "wiley" : "onlinelibrary.wiley.com",
    "jstor" : "www.jstor.org",
    "cambridge" : "www.cambridge.org",
    "mit press" : "mitpress.mit.edu",
    "oxford" : "www.oup.com",
    "rsc" : "www.rsc.org",
    "nature" : "www.nature.com",
    "cell" : "www.cell.com",
    "plos" : "journals.plos.org",
    "elsevier" : "www.elsevier.com",
    "american chemical society" : "pubs.acs.org",
    "university of california press" : "www.ucpress.edu",
    "university of chicago press" : "press.uchicago.edu",
    "hbr" : "hbr.org",
    "harvard" : "www.harvard.edu",
    "yale" : "www.yale.edu",
    "stanford" : "www.stanford.edu",
    "mit" : "www.mit.edu",
    "princeton" : "www.princeton.edu",
    "columbia" : "www.columbia.edu",
    "uc berkeley" : "www.berkeley.edu",
    "johns hopkins" : "www.jhu.edu",
    "georgetown" : "www.georgetown.edu",
    "duke" : "www.duke.edu",
    "cornell" : "www.cornell.edu",
    "rice" : "www.rice.edu",
    "carnegie mellon" : "www.cmu.edu",
    "usc" : "www.usc.edu",
    "university of washington" : "www.washington.edu",
    "nyu" : "www.nyu.edu",
    "northwestern" : "www.northwestern.edu",
    "uchicago" : "www.uchicago.edu",
    "harvard business school" : "www.hbs.edu",
    "wharton" : "www.wharton.upenn.edu",
    "rotman" : "www.rotman.utoronto.ca",
    "insead" : "www.insead.edu",
    "london business school" : "www.london.edu",
    "saïd business school" : "www.sbs.ox.ac.uk",
    "eada" : "www.eada.edu",
    "esade" : "www.esade.edu",
    "hec paris" : "www.hec.edu",
    "insead" : "www.insead.edu",
    "imf" : "www.imf.org",
    "world bank" : "www.worldbank.org",
    "united nations" : "www.un.org",
    "international monetary fund" : "www.imf.org",
    "world health organization" : "www.who.int",
    "international labour organization" : "www.ilo.org",
    "unicef" : "www.unicef.org",
    "international criminal court" : "www.icc-cpi.int",
    "red cross" : "www.redcross.org",
    "amnesty international" : "www.amnesty.org",
    "greenpeace" : "www.greenpeace.org",
    "doctors without borders" : "www.msf.org",
    "care international" : "www.care.org",
    "oxfam" : "www.oxfam.org",
    "human rights watch" : "www.hrw.org",
    "freedom house" : "freedomhouse.org",
    "international crisis group" : "www.crisisgroup.org",
    "unhcr" : "www.unhcr.org",
    "mercy corps" : "www.mercycorps.org",
    "plan international" : "www.plan-international.org",
    "save the children" : "www.savethechildren.org",
    "world wildlife fund" : "www.worldwildlife.org",
    "nature conservancy" : "www.nature.org",
    "wildlife conservation society" : "www.wcs.org",
    "national geographic" : "www.nationalgeographic.com",
    "earthjustice" : "earthjustice.org",
    "ocean conservancy" : "oceanconservancy.org",
    "surfrider foundation" : "www.surfrider.org",
    "green building council" : "www.usgbc.org",
    "sierra club" : "www.sierraclub.org",
    "350.org" : "350.org",
    "climate reality project" : "www.climaterealityproject.org",
    "rainforest alliance" : "www.rainforest-alliance.org",
    "woods hole oceanographic institution" : "www.whoi.edu",
    "george mason university" : "www.gmu.edu",
    "university of michigan" : "www.umich.edu",
    "university of california san diego" : "www.ucsd.edu",
    "university of california los angeles" : "www.ucla.edu",
    "university of california irvine" : "www.uci.edu",
    "university of california santa barbara" : "www.ucsb.edu",
    "university of california davis" : "www.ucdavis.edu",
    "university of california santa cruz" : "www.ucsc.edu",
    "university of california merced" : "www.ucmerced.edu",
    "university of california riverside" : "www.ucr.edu",
    "university of california san francisco" : "www.ucsf.edu",
    "indira gandhi national open university" : "www.ignou.ac.in",
    "university of delhi" : "www.du.ac.in",
    "jawaharlal nehru university" : "www.jnu.ac.in",
    "iit bombay" : "www.iitb.ac.in",
    "iit delhi" : "www.iitd.ac.in",
    "iit madras" : "www.iitm.ac.in",
    "iit kanpur" : "www.iitk.ac.in",
    "iit kharagpur" : "www.iitkgp.ac.in",
    "iit roorkee" : "www.iitr.ac.in",
    "iit gandhinagar" : "www.iitgn.ac.in",
    "iit hyderabad" : "www.iith.ac.in",
    "iit jodhpur" : "www.iitj.ac.in",
    "iit bhu" : "www.iitbhu.ac.in",
    "iit palakkad" : "www.iitpkd.ac.in",
    "iit bhilai" : "www.iitbhilai.ac.in",
    "iit tirupati" : "www.iittp.ac.in",
    "iit dharwad" : "www.iitdharwad.ac.in",
    "iit bhubaneswar" : "www.iitbbs.ac.in",
    "university of mumbai" : "www.mu.ac.in",
    "university of pune" : "www.unipune.ac.in",
    "banaras hindu university" : "www.bhu.ac.in",
    "jadavpur university" : "www.jaduniv.edu.in",
    "university of calcutta" : "www.caluniv.ac.in",
    "university of hyderabad" : "www.uohyd.ac.in",
    "sri venkateswara university" : "www.svu.edu.in",
    "anna university" : "www.annauniv.edu",
    "karnataka university" : "www.kud.ac.in",
    "aligarh muslim university" : "www.amu.ac.in",
    "maulana azad national institute of technology" : "www.manit.ac.in",
    "national institute of technology warangal" : "www.nitw.ac.in",
    "national institute of technology trichy" : "www.nitt.edu",
    "national institute of technology suratkal" : "www.nitk.ac.in",
    "national institute of technology rourkela" : "www.nitrkl.ac.in",
    "national institute of technology kurukshetra" : "www.nitkkr.ac.in",
    "national institute of technology jalandhar" : "www.nitj.ac.in",
    "national institute of technology silchar" : "www.nits.ac.in",
    "national institute of technology jammu" : "www.nitjammu.ac.in",
    "national institute of technology hamirpur" : "www.nith.ac.in",
    "national institute of technology delhi" : "www.nitdelhi.ac.in",
    "national institute of technology sikkim" : "www.nitsikkim.ac.in",
    "national institute of technology mizoram" : "www.nitmz.ac.in",
    "national institute of technology nagaland" : "www.nitnagaland.edu.in",
    "national institute of technology arunachal pradesh" : "www.nitap.ac.in",
    "national institute of technology uttarakhand" : "www.nituk.ac.in",
    "national institute of technology andhra pradesh" : "www.nitandhra.ac.in",
    "national institute of technology bihar" : "www.nitbihar.ac.in",
    "national institute of technology jharkhand" : "www.nitjsr.ac.in",
    "national institute of technology rajasthan" : "www.nitr.ac.in",
    "national institute of technology assam" : "www.nitassam.ac.in",
    "national institute of technology telangana" : "www.nittelangana.ac.in",
    "national institute of technology puducherry" : "www.nitpy.ac.in",
    "national institute of technology sirsa" : "www.nit-sirsa.ac.in",
    "indian institute of information technology ahmedabad" : "www.iiit.ac.in",
    "indian institute of information technology design and manufacturing kancheepuram" : "www.iiitdm.ac.in",
    "indian institute of information technology una" : "www.iiitu.ac.in",
    "indian institute of information technology kalyani" : "www.iiitkalyani.edu.in",
    "indian institute of information technology sri city" : "www.iiits.ac.in",
    "indian institute of information technology nagapattinam" : "www.iiitn.ac.in",
    "indian institute of information technology catering technology and management" : "www.iiitctm.ac.in",
    "indian institute of information technology (iiit) tiruchirappalli" : "www.iiitt.ac.in",
    "indian institute of information technology (iiit) srirangam" : "www.iiit-srirangam.ac.in",
"delhi public school": "www.dps.in",
    "the doon school": "www.doonschool.com",
    "acharya vidya kendra": "www.acharyavidyakendra.org",
    "sri ram school": "www.sriramschool.in",
    "scindia school": "www.scindia.edu",
    "saint xavier's school": "www.saintxavierschool.com",
    "bharatiya vidya bhavan": "www.bvbharatiya.org",
    "cathedral and john connon school": "www.cathedral-school.com",
    "maharishi vidya mandir": "www.mvmschools.com",
    "air force school": "www.airforceschool.com",
    "sainik school": "www.sainikschool.org",
    "krishna public school": "www.krishnapublicschool.edu.in",
    "kendriya vidyalaya": "www.kvsangathan.nic.in",
    "st. joseph's convent school": "www.stjosephconventschool.com",
    "mother's international school": "www.mothersintlschool.com",
    "bluebells school international": "www.bluebellsinternational.com",
    "the germans school": "www.germanschoolindia.com",
    "the heritage school": "www.theheritageschool.edu.in",
    "sunshine school": "www.sunshineschool.com",
    "delhi international school": "www.dis.ac.in",
    "holy child school": "www.holychildschool.org",
    "dps bangalore": "www.dpsblr.com",
    "dps faridabad": "www.dpsfaridabad.com",
    "dps r k puram": "www.dpsrkp.net",
    "lovely professional university": "www.lpu.in",
    "sri chaitanya school": "www.srichaitanya.net",
    "orchids the international school": "www.orchidsinternationalschool.com",
    "ndps": "www.ndpsschool.org",
    "shri ram global school": "www.shriramglobalschool.com",
    "swami vivekanand international school": "www.svims.edu.in",
    "manav rachna international school": "www.manavrachna.edu.in",
    "national public school": "www.npsinr.com",
    "st. francis school": "www.stfrancisschool.in",
    "the international school bangalore": "www.tisb.org",
    "the brigade school": "www.brigadeschool.com",
    "sree chitra thirunal college": "www.sct.edu.in",
    "smt. sulochanadevi singhania school": "www.ssds.edu.in",
    "jamboree education": "www.jamboreeindia.com",
    "marathi vidyalaya": "www.marathividyalaya.com",
    "maharashtra english school": "www.maharashtraenglishschool.com",
    "the montessori school": "www.montessoriindia.com",
    "shemford futuristic school": "www.shemford.com",
    "G.D Goenka Public School": "https://gdgoenka.campuscare.info/",
}
